version: '3.8'

services:
  webssh:
    build: .
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
    restart: unless-stopped
    volumes:
      - /:/host:ro  # 只讀掛載主機根目錄
    privileged: true  # 需要特權來執行命令 